import { ACCESS_PROFILE_CODES, type AccessProfileCode } from "./authorization.types.js";
import { PERMISSIONS, type Permission } from "./permissions.js";

export const FULL_ACCESS = "*" as const;

type ProfilePermission = Permission | typeof FULL_ACCESS;

export const RESOURCE_TYPES = {
  BOOTCAMP: "bootcamp",
  CONTENT: "content",
  MEDIA: "media",
  WEBINAR: "webinar",
} as const;

export type ResourceType = (typeof RESOURCE_TYPES)[keyof typeof RESOURCE_TYPES];

export const RESOURCE_SCOPES = {
  ENROLLED: "ENROLLED",
  ASSIGNED: "ASSIGNED",
  OWNED: "OWNED",
  ALL: "ALL",
} as const;

export type ResourceScope = (typeof RESOURCE_SCOPES)[keyof typeof RESOURCE_SCOPES];

export const ACCESS_PROFILES: Readonly<Record<AccessProfileCode, readonly ProfilePermission[]>> = {
  [ACCESS_PROFILE_CODES.MENTEE_DEFAULT]: [
    PERMISSIONS.BOOTCAMP_READ,
    PERMISSIONS.WEBINAR_READ,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.ENROLLMENT_CREATE,
    PERMISSIONS.BOOTCAMP_ENROLL,
    PERMISSIONS.BOOTCAMP_LEARNING_ACCESS,
  ],
  [ACCESS_PROFILE_CODES.MENTOR_DEFAULT]: [
    PERMISSIONS.BOOTCAMP_READ,
    PERMISSIONS.BOOTCAMP_CREATE,
    PERMISSIONS.BOOTCAMP_UPDATE,
    PERMISSIONS.BOOTCAMP_MANAGE_SESSIONS,
    PERMISSIONS.BOOTCAMP_ENROLLMENT_KEY_MANAGE,
    PERMISSIONS.BOOTCAMP_PARTICIPANT_READ,
    PERMISSIONS.BOOTCAMP_MENTOR_JOIN,
    PERMISSIONS.WEBINAR_READ,
    PERMISSIONS.WEBINAR_CREATE,
    PERMISSIONS.WEBINAR_UPDATE,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.MEDIA_UPLOAD,
    PERMISSIONS.MEDIA_DELETE,
  ],
  [ACCESS_PROFILE_CODES.EXECUTIVE_READ]: [
    PERMISSIONS.ANALYTICS_READ_EXECUTIVE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.BOOTCAMP_READ,
    PERMISSIONS.WEBINAR_READ,
    PERMISSIONS.CONTENT_READ,
  ],
  [ACCESS_PROFILE_CODES.OPERATIONS_FULL]: [
    PERMISSIONS.BOOTCAMP_READ,
    PERMISSIONS.BOOTCAMP_CREATE,
    PERMISSIONS.BOOTCAMP_UPDATE,
    PERMISSIONS.BOOTCAMP_PUBLISH,
    PERMISSIONS.BOOTCAMP_MANAGE_SESSIONS,
    PERMISSIONS.BOOTCAMP_MANAGE_ENROLLMENT,
    PERMISSIONS.BOOTCAMP_ENROLLMENT_KEY_MANAGE,
    PERMISSIONS.BOOTCAMP_PARTICIPANT_READ,
    PERMISSIONS.BOOTCAMP_MENTOR_ASSIGN,
    PERMISSIONS.ENROLLMENT_MANAGE,
    PERMISSIONS.WEBINAR_READ,
    PERMISSIONS.WEBINAR_CREATE,
    PERMISSIONS.WEBINAR_UPDATE,
    PERMISSIONS.WEBINAR_PUBLISH,
    PERMISSIONS.MEDIA_UPLOAD,
    PERMISSIONS.MEDIA_DELETE,
  ],
  [ACCESS_PROFILE_CODES.MARKETING_FULL]: [
    PERMISSIONS.BOOTCAMP_MANAGE_VISUAL,
    PERMISSIONS.WEBINAR_MANAGE_VISUAL,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.CONTENT_PUBLISH,
    PERMISSIONS.CONTENT_MANAGE_VISUAL,
    PERMISSIONS.MEDIA_UPLOAD,
    PERMISSIONS.MEDIA_DELETE,
  ],
  [ACCESS_PROFILE_CODES.SUPERADMIN]: [FULL_ACCESS],
};

export const ACCESS_PROFILE_SCOPES: Readonly<
  Record<AccessProfileCode, Readonly<Partial<Record<ResourceType, ResourceScope>>>>
> = {
  [ACCESS_PROFILE_CODES.MENTEE_DEFAULT]: {
    [RESOURCE_TYPES.BOOTCAMP]: RESOURCE_SCOPES.ENROLLED,
  },
  [ACCESS_PROFILE_CODES.MENTOR_DEFAULT]: {
    [RESOURCE_TYPES.BOOTCAMP]: RESOURCE_SCOPES.ASSIGNED,
    [RESOURCE_TYPES.CONTENT]: RESOURCE_SCOPES.OWNED,
    [RESOURCE_TYPES.MEDIA]: RESOURCE_SCOPES.OWNED,
    [RESOURCE_TYPES.WEBINAR]: RESOURCE_SCOPES.OWNED,
  },
  [ACCESS_PROFILE_CODES.EXECUTIVE_READ]: {
    [RESOURCE_TYPES.BOOTCAMP]: RESOURCE_SCOPES.ALL,
    [RESOURCE_TYPES.CONTENT]: RESOURCE_SCOPES.ALL,
    [RESOURCE_TYPES.WEBINAR]: RESOURCE_SCOPES.ALL,
  },
  [ACCESS_PROFILE_CODES.OPERATIONS_FULL]: {
    [RESOURCE_TYPES.BOOTCAMP]: RESOURCE_SCOPES.ALL,
    [RESOURCE_TYPES.MEDIA]: RESOURCE_SCOPES.ALL,
    [RESOURCE_TYPES.WEBINAR]: RESOURCE_SCOPES.ALL,
  },
  [ACCESS_PROFILE_CODES.MARKETING_FULL]: {
    [RESOURCE_TYPES.BOOTCAMP]: RESOURCE_SCOPES.ALL,
    [RESOURCE_TYPES.CONTENT]: RESOURCE_SCOPES.ALL,
    [RESOURCE_TYPES.MEDIA]: RESOURCE_SCOPES.ALL,
    [RESOURCE_TYPES.WEBINAR]: RESOURCE_SCOPES.ALL,
  },
  [ACCESS_PROFILE_CODES.SUPERADMIN]: {
    [RESOURCE_TYPES.BOOTCAMP]: RESOURCE_SCOPES.ALL,
    [RESOURCE_TYPES.CONTENT]: RESOURCE_SCOPES.ALL,
    [RESOURCE_TYPES.MEDIA]: RESOURCE_SCOPES.ALL,
    [RESOURCE_TYPES.WEBINAR]: RESOURCE_SCOPES.ALL,
  },
};

export function configuredResourceScope(
  accessProfileCode: AccessProfileCode,
  resourceType: ResourceType,
): ResourceScope | null {
  return ACCESS_PROFILE_SCOPES[accessProfileCode][resourceType] ?? null;
}
