import { ACCESS_PROFILE_CODES, type AccessProfileCode } from "./authorization.types";
import { PERMISSIONS, type Permission } from "./permissions";

export const FULL_ACCESS = "*" as const;

type ProfilePermission = Permission | typeof FULL_ACCESS;

export const ACCESS_PROFILES: Readonly<Record<AccessProfileCode, readonly ProfilePermission[]>> = {
  [ACCESS_PROFILE_CODES.MENTEE_DEFAULT]: [
    PERMISSIONS.BOOTCAMP_READ,
    PERMISSIONS.WEBINAR_READ,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.ENROLLMENT_CREATE,
    PERMISSIONS.ENROLLMENT_READ_OWN,
    PERMISSIONS.BOOTCAMP_ENROLL,
  ],
  [ACCESS_PROFILE_CODES.MENTOR_DEFAULT]: [
    PERMISSIONS.BOOTCAMP_READ,
    PERMISSIONS.BOOTCAMP_CREATE,
    PERMISSIONS.BOOTCAMP_UPDATE,
    PERMISSIONS.BOOTCAMP_MANAGE_SESSIONS,
    PERMISSIONS.BOOTCAMP_ENROLLMENT_KEY_MANAGE,
    PERMISSIONS.BOOTCAMP_PARTICIPANT_READ,
    PERMISSIONS.BOOTCAMP_MENTOR_JOIN,
    PERMISSIONS.WEBINAR_READ,
    PERMISSIONS.WEBINAR_CREATE,
    PERMISSIONS.WEBINAR_UPDATE,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_UPDATE,
  ],
  [ACCESS_PROFILE_CODES.EXECUTIVE_READ]: [
    PERMISSIONS.ANALYTICS_READ_EXECUTIVE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.BOOTCAMP_READ,
    PERMISSIONS.WEBINAR_READ,
    PERMISSIONS.CONTENT_READ,
  ],
  [ACCESS_PROFILE_CODES.OPERATIONS_FULL]: [
    PERMISSIONS.BOOTCAMP_READ,
    PERMISSIONS.BOOTCAMP_CREATE,
    PERMISSIONS.BOOTCAMP_UPDATE,
    PERMISSIONS.BOOTCAMP_PUBLISH,
    PERMISSIONS.BOOTCAMP_MANAGE_ALL,
    PERMISSIONS.BOOTCAMP_MANAGE_SESSIONS,
    PERMISSIONS.BOOTCAMP_MANAGE_ENROLLMENT,
    PERMISSIONS.BOOTCAMP_ENROLLMENT_KEY_MANAGE,
    PERMISSIONS.BOOTCAMP_PARTICIPANT_READ,
    PERMISSIONS.BOOTCAMP_MENTOR_ASSIGN,
    PERMISSIONS.ENROLLMENT_MANAGE,
    PERMISSIONS.WEBINAR_READ,
    PERMISSIONS.WEBINAR_CREATE,
    PERMISSIONS.WEBINAR_UPDATE,
    PERMISSIONS.WEBINAR_PUBLISH,
    PERMISSIONS.WEBINAR_MANAGE_ALL,
  ],
  [ACCESS_PROFILE_CODES.MARKETING_FULL]: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.CONTENT_PUBLISH,
    PERMISSIONS.CONTENT_MANAGE_VISUAL,
    PERMISSIONS.CONTENT_MANAGE_ALL,
  ],
  [ACCESS_PROFILE_CODES.SUPERADMIN]: [FULL_ACCESS],
};
