import {
  ACCESS_PROFILE_CODES,
  ROLES,
  type AccessProfileCode,
  type RoleCode,
} from "./authorization.types.js";

export const ROLE_DEFAULT_ACCESS: Readonly<Record<RoleCode, AccessProfileCode>> = {
  [ROLES.MENTEE]: ACCESS_PROFILE_CODES.MENTEE_DEFAULT,
  [ROLES.MENTOR]: ACCESS_PROFILE_CODES.MENTOR_DEFAULT,
  [ROLES.CEO]: ACCESS_PROFILE_CODES.EXECUTIVE_READ,
  [ROLES.COO]: ACCESS_PROFILE_CODES.OPERATIONS_FULL,
  [ROLES.CMO]: ACCESS_PROFILE_CODES.MARKETING_FULL,
  [ROLES.SUPERADMIN]: ACCESS_PROFILE_CODES.SUPERADMIN,
};
